version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/ai-tools:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - ELECTRON_DISABLE_SECURITY_WARNINGS=true
      - DISPLAY=:99
    ports:
      - "3000:3000"
      - "8080:8080"
      - "9229:9229"
    networks:
      - dev-network

  # Optional: Add a database service if needed
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ai_tools_dev
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - dev-network

  # Optional: Add a Redis service if needed
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - dev-network

networks:
  dev-network:
    driver: bridge

# volumes:
#   postgres_data:








